# Generated by Django 3.2.15 on 2024-11-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('log_search', '0082_auto_20241113_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindexset',
            name='chart_configs',
            field=models.JSONField(default=dict, null=True, verbose_name='图表相关配置'),
        ),
    ]
